### PR TITLE
Updated Folder Structure

### PR DESCRIPTION
**Pull request by RiyaMathew-11**

### CODE REVIEW

**Comment by knadh** [comment]
Let's fix the directory names. Convention for directory names is:
- All lowercase (unless there's an explicit reason for uppercase)
- No spaces. Dashes instead.

Brand name is `mon school` (all lowercase). Here, the ideal directory name is just `monschool`.

**Comment by RiyaMathew-11** [comment]
Ok 👍 
Will fix now.

**Comment by knadh** [comment]
Sorry, missed to point this out earlier. Let's make all directory and filenames lowercase.

eg: `asset/IndiaFOSS/IndiaFOSS.svg` -> `asset/indiafoss/indiafoss.svg`

**Comment by RiyaMathew-11** [comment]
No worries. Will change it too and commit

**Pull request merged**
